### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Zama15** [BrightCoders-Institute/s5a1-administrador-de-eventos-team-03-s5a1-administrador-de-eventos#1]
- Requirements
Create the mockup of the landing page

- Design
![Screenshot from 2024-01-23 18-32-56](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-03-s5a1-administrador-de-eventos/assets/112733483/e4f92f75-5dc0-4fde-9d9d-fb869ae79e90)

- Criteria
- [ ] start the protect as mobile first 
- [ ] use the colors palette; blue: #0139A6, white: #EBF5EE, yellow: #F9C80E
- [ ] body margin are: mobile 16px left-right, desktop 32px left-right

**Comment by farellano0** [comment]
Design Desktop:
![image](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team-03-s5a1-administrador-de-eventos/assets/73454963/cdbd0667-a399-4fd2-8266-730eba7f573d)
